### PR TITLE
Raspbian Stretch instructions

### PR DESCRIPTION
**Pull request by bobloy**
## Before PR

 - [x] Added frontmatter header to your doc based on [this guide](/README.MD)
 - [x] Formatted the doc to fit jekyll requirements based on [this guide](/README.MD)
 - [x] Added link to a sidebar based on [this guide](/README.MD)

## Doc info
Please provide a required info on your PR

 * Category:  Guides
 * Subject: Raspbian Stretch installation instructions
 * Author: Sinbad/Bobloy

### CODE REVIEW

**Comment by Twentysix26** [comment]
I'll try to check and get this merged tomorrow

**Comment by Twentysix26** [comment]
@bobloy I noticed that this guide installs the requirements contained in **requirements_no_audio.txt**
At the same time, at the end it asks the user to switch player to supposedly use avconv.
However from [other sources](https://raspberrypi.stackexchange.com/a/75824) I have read that Raspbian Stretch has ffmpeg installed by default.
Could you please clarify what happens when following this installation? Does the user end up with an installation without audio or...?

**Comment by bobloy** [comment]
Hmm, I'll re-run the installation on one of my pi's this evening and let you know.

**Comment by bobloy** [comment]
Added correct audio instructions

**Comment by Twentysix26** [comment]
Thanks, my original question remains unanswered though. Could you please clarify?

**Comment by bobloy** [comment]
I did not find ffmpeg to be installed by default on a fresh raspberry pi, though it was easily installed with apt-get.

I updated the guide to reflect that.

**Comment by Twentysix26** [comment]
Alright, was audio working after that? I'm asking because there is still
> sudo python3.5 -m pip install -r requirements_no_audio.txt

which makes me doubt it. If you confirm it I'll just go ahead and merge, corrections can be made later anyway.

**Comment by bobloy** [comment]
Hmmm.. Now you've got me doubting myself, I'll double check this evening

**Pull request merged**
